name: Go build ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        working-directory: ./server
        run: go mod download

      - name: Run gofmt
        working-directory: ./server
        run: |
          fmt_output=$(gofmt -l .)
          if [ -n "$fmt_output" ]; then
            echo " Files not properly formatted:"
            echo "$fmt_output"
            exit 1
          fi

      - name: Run go vet
        working-directory: ./server
        run: go vet ./...

      - name: Build API
        working-directory: ./server
        run: go build -tags sqlite ./cmd/api

      - name: Build Migrations
        working-directory: ./server
        run: go build -tags sqlite ./cmd/migrate/migrations
